GET  https://fullstackopen-helsinki-mrtw.onrender.com/api/persons
###
GET  https://fullstackopen-helsinki-mrtw.onrender.com/api/persons/4

###
POST  https://fullstackopen-helsinki-mrtw.onrender.com/api/persons HTTP/1.1
content-type: application/json

{
    "name": "samp2adf",
    "number": "1232141"
}

###
POST  http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "name": "haoq",
    "number": "23-1232141"
}

